routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        // Member Type
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        // Class
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
		// Bank
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');
        // Asset Category
        Route::resource('asset-category', 'PdtCategoryAssetController');
        Route::get('table/asset-category', 'PdtCategoryAssetController@dataTable')->name('table.asset-category');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        // Employee
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        // Banner
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        // Asset
        Route::resource('asset', 'PdtAssetController');
        Route::get('table/asset', 'PdtAssetController@dataTable')->name('table.asset');
    });
    // Setting
    Route::group(['prefix'=>'setting'], function(){
       // Module
        Route::resource('menu', 'SecModuleController');
        Route::get('table/menu', 'SecModuleController@dataTable')->name('table.menu'); 
    });
		
	Route::get('/master/class_price','ClassPriceController@index');
	Route::get('/master/class_price/create','ClassPriceController@create');
	Route::get('/master/class_price/delete/{id}','ClassPriceController@destroy');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::post('/master/class_price/post_price/','ClassPriceController@store');
	Route::post('/master/class_price/edit_price/{id}','ClassPriceController@update');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::get('/master/class_price/show/{id}','ClassPriceController@show');
	
	Route::get('/master/country','CountryController@index');
	Route::get('/master/country/create','CountryController@create');
	Route::post('/master/country/post_country','CountryController@store');
	Route::get('/master/country/edit/{id}','CountryController@edit');
	Route::post('/master/country/edit_country/{id}','CountryController@update');
	Route::get('/master/country/import','CountryController@import');
	Route::post('/master/country/proses_import','CountryController@proses_import');

	Route::get('/master/province','ProvinceController@index');
	Route::get('/master/province/create','ProvinceController@create');
	Route::post('/master/province/post_province','ProvinceController@store');
	Route::post('/master/province/edit_province/{id}','ProvinceController@update');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/edit/{id}','ProvinceController@edit');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/import','ProvinceController@import');
	Route::post('/master/province/import_province','ProvinceController@import_province');
	
	Route::get('/master/regency','RegencyController@index');
	Route::get('/master/regency/create','RegencyController@create');
	Route::post('/master/regency/post_regency','RegencyController@store');
	Route::get('/master/regency/edit_regency/{id}','RegencyController@edit');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/delete_regency/{id}','RegencyController@destroy');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/import','RegencyController@import');
	Route::post('/master/regency/import_post_regency','RegencyController@import_regency');
	
	Route::get('/master/district','DistrictController@index');
	Route::get('/master/district/create','DistrictController@create');
	Route::post('/master/district/post_district','DistrictController@store');
	Route::get('master/district/edit/{id}','DistrictController@edit');
	Route::post('/master/district/edit_district/{id}','DistrictController@update');
	Route::get('/master/district/delete_district/{id}','DistrictController@destroy');
	Route::get('/master/district/import','DistrictController@import');
	Route::post('/master/district/import_district','DistrictController@import_district');
	
	Route::get('/master/village','VillageController@index');
	Route::get('/master/village/create','VillageController@create');
	Route::post('/master/village/post_village','VillageController@store');
	Route::get('master/village/edit_village/{id}','VillageController@edit');
	Route::post('/master/village/edit_village_post/{id}','VillageController@update');
	Route::get('/master/village/delete_village/{id}','VillageController@destroy');
	Route::get('/master/village/import','VillageController@import');
	Route::post('/master/village/import_village','VillageController@import_village');
	
	
	Route::get('/master/data_address','MstAddressController@index');
	Route::get('/master/address/create','MstAddressController@create');
	Route::get('/master/address/province/{id}','MstAddressController@province');
	Route::get('/master/address/regency/{id}','MstAddressController@regency');
	Route::get('/master/address/district/{id}','MstAddressController@district');
	Route::get('/master/address/village/{id}','MstAddressController@village');
	Route::post('/master/address/post_address','MstAddressController@store');
});





// Route::get('/home', 'HomeController@index')->name('home');

resources/views/base/action.blade.php
<a href="{{ $url_show }}" class="btn-show btn btn-xs btn-primary" title="Detail {{ $model->role }}"><i class="fa fa-search"></i></a>
<a href="{{ $url_edit }}" class="modal-show btn btn-xs btn-primary edit" title="Edit {{ $model->role }}"><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete {{ $model->role }}"><i class="fa fa-trash"></i></a>

resources/views/base/footer.blade.php
<footer class="main-footer">
<div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
</div>
<strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
reserved.
</footer>

resources/views/base/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Kopaja | @yield('title')</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{asset('theme/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('theme/bower_components/font-awesome/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('theme/bower_components/Ionicons/css/ionicons.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('theme/dist/css/AdminLTE.min.css')}}">
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('theme/plugins/iCheck/square/blue.css') }}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
    folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset('theme/dist/css/skins/_all-skins.min.css')}}">
<!-- Morris chart -->
{{-- <link rel="stylesheet" href="{{asset('theme/bower_components/morris.js/morris.css')}}"> --}}
<!-- jvectormap -->
{{-- <link rel="stylesheet" href="{{asset('theme/bower_components/jvectormap/jquery-jvectormap.css')}}"> --}}
<!-- Date Picker -->
<link rel="stylesheet" href="{{asset('theme/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{asset('theme/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('theme/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">

<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('theme/assets/vendor/datatables/datatables.min.css') }}">
<!-- IE10 -->
<link rel="stylesheet" href="{{ asset('theme/assets/css/ie10-viewport-bug-workaround.css') }}">
<!-- Emulation Modes Warning -->
<link rel="stylesheet" href="{{ asset('theme/assets/js/ie-emulation-modes-warning.js') }}">

<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
<style>
    .table { font-size: 14px; }
</style>

@stack('css')

resources/views/base/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('base.head')
</head>
<body class="hold-transition skin-blue fixed sidebar-mini">
    <div class="wrapper">
        
        @include('base.nav')
        
        @include('base.menu')

        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @yield('page_icon')
                    @yield('page_title')
                    <small>@yield('page_subtitle')</small>
                </h1>
                @yield('breadcrumb')
            </section>

            <section class="content">
                {{-- flash message --}}
                @if(session()->get('success'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        {{ session()->get('success') }} 
                    </div>
                @elseif(session()->get('error'))
                    <div class="alert alert-error alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        {{ session()->get('error') }}  
                    </div>
                @endif
                {{-- menu --}}
                @yield('menu')
                {{-- content --}}
                @yield('content')
            </section>
        </div>
        @include('base.modal')

        @include('base.footer')

        <div class="control-sidebar-bg"></div>
    </div>

    @include('base.script')
</body>
</html>

resources/views/base/menu.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('images/employee/'.Auth::user()->photo) }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->full_name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
{{-- Dashboard --}}
            <li class="treeview {{ Request::is('site') || Request::is('/') ? 'active' : null }}">
                <a href="{{ route('site.index') }}">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ Request::is('site.index') ? 'active' : null }}">
                    	<a href="{{ route('site.index') }}">
                            <i class="fa fa-circle-o"></i> Aset Terlaris
                        </a>
                    </li>
                    <li class="{{ Request::is('site.index') ? 'active' : null }}">
                    	<a href="{{ route('site.index') }}">
                            <i class="fa fa-circle-o"></i> Investor Tertinggi
                        </a>
                    </li>
                </ul>
            </li>
{{-- End Dashboard --}}
{{-- Master --}}
            <li class="treeview {{ Request::is('master/*') ? 'active' : null }}">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Master</span>
                </a>
                <ul class="treeview-menu">
                   
                    <li class="{{ Request::is('master/member') ? 'active' : null }}">
                        <a href="{{ route('member.index') }}">
                            <i class="fa fa-circle-o"></i> Member
                        </a>
                    </li>
					
                    <li class="{{ Request::is('master/bank') || Request::is('master/bank/*') ? 'active' : null }}">
                        <a href="{{ route('bank.index') }}">
                            <i class="fa fa-circle-o"></i> Bank
                        </a>
                    </li>
					
					<li class="treeview {{ Request::is('master/class') || Request::is('master/class/*') || Request::is('master/class_price') || Request::is('master/class_price/*') ? 'active' : null }}">
						<a href="#">
		                    <i class="fa fa-folder"></i> <span>Class</span>
		                </a>
						<ul class="treeview-menu">    
		                    <li class="{{ Request::is('master/class') ? 'active' : null }}">
		                        <a href="{{ route('class.index') }}">
		                            <i class="fa fa-circle-o"></i> Data Class
		                        </a>
		                    </li>
							
							 <li class="{{ Request::is('master/class_price') ? 'active' : null }}">
		                        <a href="/master/class_price">
		                            <i class="fa fa-circle-o"></i> Price Class
		                        </a>
		                    </li>
						</ul>
					</li>
					
					<li class="treeview {{ Request::is('location/*') ? 'active' : null }}">
		                <a href="#">
		                    <i class="fa fa-folder"></i> <span>Address</span>
		                </a>
		                <ul class="treeview-menu">
		                    
							<!--li class="{{ Request::is('location/address') ? 'active' : null }}">
					                        <a href="/master/data_address">
					                            <i class="fa fa-circle-o"></i> Data Address
					                        </a>
					                    </li-->
										
							<li class="{{ Request::is('location/country') ? 'active' : null }}">
		                        <a href="/master/country">
		                            <i class="fa fa-circle-o"></i> Country
		                        </a>
		                    </li>
							
							<li class="{{ Request::is('location/province') ? 'active' : null }}">
		                        <a href="/master/province">
		                            <i class="fa fa-circle-o"></i> Province
		                        </a>
		                    </li>
							
							<li class="{{ Request::is('location/regency') ? 'active' : null }}">
		                        <a href="/master/regency">
		                            <i class="fa fa-circle-o"></i> Regency
		                        </a>
		                    </li>
							
							<li class="{{ Request::is('location/district') ? 'active' : null }}">
		                        <a href="/master/district">
		                            <i class="fa fa-circle-o"></i> District
		                        </a>
		                    </li>
							
							<li class="{{ Request::is('location/village') ? 'active' : null }}">
		                        <a href="/master/village">
		                            <i class="fa fa-circle-o"></i> Village
		                        </a>
		                    </li>
		                </ul>
		            </li>

		            <li class="{{ Request::is('master/employee') || Request::is('master/employee/*') ? 'active' : null }}">
						<a href="{{ route('employee.index') }}">
							<i class="fa fa-circle-o"></i> Employee
						</a>
					</li>

					<li class="{{ Request::is('master/position') ? 'active' : null }}">
						<a href="{{ route('position.index') }}">
							<i class="fa fa-circle-o"></i> Position
						</a>
					</li>
					
					<li class="{{ Request::is('master/page') ? 'active' : null }}">
						<a href="{{ route('page.index') }}">
							<i class="fa fa-circle-o"></i> Page
						</a>
					</li>
					
					<li class="{{ Request::is('master/banner') || Request::is('master/banner/*') ? 'active' : null }}">
						<a href="{{ route('banner.index') }}">
							<i class="fa fa-circle-o"></i> Banner
						</a>
					</li>
					
					<li class="{{ Request::is('master/terms-conds') || Request::is('master/terms-conds/*') ? 'active' : null }}">
						<a href="{{ route('terms-conds.index') }}">
							<i class="fa fa-circle-o"></i> Term and Condition
						</a>
					</li>
					
					<li class="treeview {{ Request::is('asset/*') ? 'active' : null }}">
						<a href="#">
		                    <i class="fa fa-folder"></i> <span>Asset</span>
		                </a>
						<ul class="treeview-menu">    
		                    <li class="{{ Request::is('master/asset-category') ? 'active' : null }}">
		                        <a href="{{ route('asset-category.index') }}">
		                            <i class="fa fa-circle-o"></i> Category 
		                        </a>
		                    </li>
							 <li class="{{ Request::is('master/asset') ? 'active' : null }}">
		                        <a href="#">
		                            <i class="fa fa-circle-o"></i>  Asset
		                        </a>
		                    </li>
						</ul>
					</li>

					<li class="treeview {{ Request::is('news/*') ? 'active' : null }}">
		                <a href="#">
		                    <i class="fa fa-folder"></i> <span>News</span>
		                </a>
		                <ul class="treeview-menu">
						
							<li class="{{ Request::is('asset/category') ? 'active' : null }}">
		                        <a href="#">
		                            <i class="fa fa-circle-o"></i> Category News
		                        </a>
		                    </li>
							
							
		                    <li class="{{ Request::is('asset/tag') ? 'active' : null }}">
		                        <a href="#">
		                            <i class="fa fa-circle-o"></i> Tag News
		                        </a>
		                    </li>
							
							<li class="{{ Request::is('asset/data') ? 'active' : null }}">
		                        <a href="#">
		                            <i class="fa fa-circle-o"></i> Data News
		                        </a>
		                    </li>
							
		                </ul>
		            </li>
					
                    <li class="{{ Request::is('master/help') ? 'active' : null }}">
                        <a href="{{ route('help.index') }}">
                            <i class="fa fa-circle-o"></i> Help
                        </a>
                    </li>

                    <li class="{{ Request::is('privacy_policy') ? 'active' : null }}">
						<a href="#">
							<i class="fa fa-circle-o"></i> Privacy Policy
						</a>
					</li>
					
					<li class="{{ Request::is('contact_us') ? 'active' : null }}">
						<a href="#">
							<i class="fa fa-circle-o"></i> Contact Us
						</a>
					</li>

                </ul>
            </li>
{{-- End Master --}}	
{{-- Transaction --}}
			<li class="treeview {{ Request::is('transaction/*') ? 'active' : null }}">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Transaction</span>
                </a>
                <ul class="treeview-menu">
				
					<li class="{{ Request::is('transcation/investor') ? 'active' : null }}">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Investor Details
                        </a>
                    </li>					
				
                </ul>
            </li>
{{-- End Transaction --}}
{{-- Setting --}}
            <li class="treeview {{ Request::is('setting/*') ? 'active' : null }}">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Setting</span>
                </a>
                <ul class="treeview-menu">
				
					<li class="{{ Request::is('master/role') ? 'active' : null }}">
                        <a href="{{ route('role.index') }}">
                            <i class="fa fa-circle-o"></i> Role
                        </a>
                    </li>
					
                    <li class="{{ Request::is('setting/menu') ? 'active' : null }}">
                        <a href="{{ route('menu.index') }}">
                            <i class="fa fa-circle-o"></i> Menu
                        </a>
                    </li>
					
					<li class="{{ Request::is('setting/sec_accessrole') ? 'active' : null }}">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Access Role
                        </a>
                    </li>
					
					<li class="{{ Request::is('setting/sec_accessuser') ? 'active' : null }}">
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Access User
                        </a>
                    </li>
					
                </ul>
            </li>
{{-- End Setting --}}		
        </ul>
    </section>
<!-- /.sidebar -->
</aside>

resources/views/base/modal.blade.php
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-title">Modal Title</h4>
            </div>
            <div class="modal-body" id="modal-body">
            
            </div>
            <div class="modal-footer" id="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="modal-btn-save">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/base/nav.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="{{ URL::to('/') }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>K</b>A</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>KOP</b>AJA</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ asset('images/employee/'.Auth::user()->photo) }}" class="user-image" alt="User Image">
                    <span class="hidden-xs">{{ Auth::user()->full_name }}</span>
                </a>
                <ul class="dropdown-menu">
                    <!-- User image -->
                    <li class="user-header">
                    <img src="{{ asset('images/employee/'.Auth::user()->photo) }}" class="img-circle" alt="User Image">

                    <p>
                        {{ Auth::user()->full_name }}
                    </p>
                    </li>
                    <!-- Menu Body -->
                    <!-- Menu Footer-->
                    <li class="user-footer">
                    <div class="pull-left">
                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Sign out</a>
                        
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </div>
                    </li>
                </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>