routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        // Member Type
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        // Class
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
		// Bank
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');
        // Asset Category
        Route::resource('asset-category', 'PdtCategoryAssetController');
        Route::get('table/asset-category', 'PdtCategoryAssetController@dataTable')->name('table.asset-category');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        // Employee
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        // Banner
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        // Asset
        Route::resource('asset', 'PdtAssetController');
        Route::get('table/asset', 'PdtAssetController@dataTable')->name('table.asset');
    });
    // Setting
    Route::group(['prefix'=>'setting'], function(){
       // Module
        Route::resource('menu', 'SecModuleController');
        Route::get('table/menu', 'SecModuleController@dataTable')->name('table.menu'); 
    });
		
	Route::get('/master/class_price','ClassPriceController@index');
	Route::get('/master/class_price/create','ClassPriceController@create');
	Route::get('/master/class_price/delete/{id}','ClassPriceController@destroy');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::post('/master/class_price/post_price/','ClassPriceController@store');
	Route::post('/master/class_price/edit_price/{id}','ClassPriceController@update');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::get('/master/class_price/show/{id}','ClassPriceController@show');
	
	Route::get('/master/country','CountryController@index');
	Route::get('/master/country/create','CountryController@create');
	Route::post('/master/country/post_country','CountryController@store');
	Route::get('/master/country/edit/{id}','CountryController@edit');
	Route::post('/master/country/edit_country/{id}','CountryController@update');
	Route::get('/master/country/import','CountryController@import');
	Route::post('/master/country/proses_import','CountryController@proses_import');

	Route::get('/master/province','ProvinceController@index');
	Route::get('/master/province/create','ProvinceController@create');
	Route::post('/master/province/post_province','ProvinceController@store');
	Route::post('/master/province/edit_province/{id}','ProvinceController@update');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/edit/{id}','ProvinceController@edit');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/import','ProvinceController@import');
	Route::post('/master/province/import_province','ProvinceController@import_province');
	
	Route::get('/master/regency','RegencyController@index');
	Route::get('/master/regency/create','RegencyController@create');
	Route::post('/master/regency/post_regency','RegencyController@store');
	Route::get('/master/regency/edit_regency/{id}','RegencyController@edit');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/delete_regency/{id}','RegencyController@destroy');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/import','RegencyController@import');
	Route::post('/master/regency/import_post_regency','RegencyController@import_regency');
	
	Route::get('/master/district','DistrictController@index');
	Route::get('/master/district/create','DistrictController@create');
	Route::post('/master/district/post_district','DistrictController@store');
	Route::get('master/district/edit/{id}','DistrictController@edit');
	Route::post('/master/district/edit_district/{id}','DistrictController@update');
	Route::get('/master/district/delete_district/{id}','DistrictController@destroy');
	Route::get('/master/district/import','DistrictController@import');
	Route::post('/master/district/import_district','DistrictController@import_district');
	
	Route::get('/master/village','VillageController@index');
	Route::get('/master/village/create','VillageController@create');
	Route::post('/master/village/post_village','VillageController@store');
	Route::get('master/village/edit_village/{id}','VillageController@edit');
	Route::post('/master/village/edit_village_post/{id}','VillageController@update');
	Route::get('/master/village/delete_village/{id}','VillageController@destroy');
	Route::get('/master/village/import','VillageController@import');
	Route::post('/master/village/import_village','VillageController@import_village');
	
	
	Route::get('/master/data_address','MstAddressController@index');
	Route::get('/master/address/create','MstAddressController@create');
	Route::get('/master/address/province/{id}','MstAddressController@province');
	Route::get('/master/address/regency/{id}','MstAddressController@regency');
	Route::get('/master/address/district/{id}','MstAddressController@district');
	Route::get('/master/address/village/{id}','MstAddressController@village');
	Route::post('/master/address/post_address','MstAddressController@store');
});





// Route::get('/home', 'HomeController@index')->name('home');

resources/views/master/asset/action.blade.php
<a href="{{ $url_show }}" class="btn btn-xs btn-primary" title="Detail "><i class="fa fa-search"></i></a>
<a href="{{ $url_edit }}" class="btn btn-xs btn-primary" title="Edit "><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete "><i class="fa fa-trash"></i></a>

resources/views/master/asset/create.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Create Asset @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('asset.index') }}" class="btn btn-success" title="Manage Asset">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    {!! Form::model($model, [
        'route' => 'asset.store',
        'method'=> 'post',
        'enctype'   => 'multipart/form-data'
    ]) !!}
    <div class="box-body">
        @if(count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                    <li>{{  $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <h4>Asset</h4>
        <div class="row">
        	<div class="col-md-8">
        		<div class="form-group">
                    <label for="asset_name" class="control-label">Nama*</label>
                    {!! Form::text('asset_name', null, ['class'=>'form-control', 'id'=>'asset_name']) !!}

                    @if($errors->has('asset_name'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('asset_name') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
                <div class="form-group">
                    <label for="category_asset_id" class="control-label">Kategori*</label>
                    {!! Form::select('category_asset_id', [''=>'- Select -'] + $category, null, ['class'=>'form-control', 'id'=>'category_asset_id']) !!}

                    @if($errors->has('category_asset_id'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('category_asset_id') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		
        	</div>
        </div>
        <div class="row">
        	<div class="col-md-12">
        		<div class="form-group">
                    <label for="desc" class="control-label">Deskripsi*</label>
                    {!! Form::textarea('desc', null, ['class'=>'form-control textarea', 'id'=>'desc', 'rows'=>6]) !!}

                    @if($errors->has('desc'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('desc') }}
                        </span>
                    @endif
                </div>
        	</div>
        </div>
        <div class="row">
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="price_njop" class="control-label">Harga NJOP*</label>
                    <div class="input-group">
                    	<span class="input-group-addon">
                    		Rp
                    	</span>
                    	{!! Form::text('price_njop', null, ['class'=>'form-control', 'id'=>'price_njop']) !!}
                    </div>

                    @if($errors->has('price_njop'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('price_njop') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="price_market" class="control-label">Harga Pasar*</label>
                    <div class="input-group">
                    	<span class="input-group-addon">
                    		Rp
                    	</span>
                    	{!! Form::text('price_market', null, ['class'=>'form-control', 'id'=>'price_market']) !!}
                    </div>

                    @if($errors->has('price_market'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('price_market') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="credit_tenor" class="control-label">Tenor Kredit*</label>
                    <div class="input-group">
                    	<span class="input-group-addon">
                    		Rp
                    	</span>
                    	{!! Form::text('credit_tenor', null, ['class'=>'form-control', 'id'=>'credit_tenor']) !!}
                    </div>

                    @if($errors->has('credit_tenor'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('credit_tenor') }}
                        </span>
                    @endif
                </div>
        	</div>
        </div>
        <div class="row">
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="invesment_tenor" class="control-label">Tenor Investasi*</label>
                    <div class="input-group">
                    	<span class="input-group-addon">
                    		Rp
                    	</span>
                    	{!! Form::text('invesment_tenor', null, ['class'=>'form-control', 'id'=>'invesment_tenor']) !!}
                    </div>

                    @if($errors->has('invesment_tenor'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('invesment_tenor') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="terms_conds_id" class="control-label">Term & Conditions*</label>
                    {!! Form::select('terms_conds_id', [''=>'- Select -'] + $termsconds, null, ['class'=>'form-control', 'id'=>'terms_conds_id']) !!}

                    @if($errors->has('terms_conds_id'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('terms_conds_id') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="file_resume" class="control-label">File Resume*</label>
                    {!! Form::file('file_resume', ['accept'=>'.pdf']) !!}

                    @if($errors->has('file_resume'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('file_resume') }}
                        </span>
                    @endif
                </div>
        	</div>
        </div>
        <div class="row">
        	{{-- <div class="col-md-6">
        		<label for="images" class="control-label">Atribut</label>
		        <div class="form-group">
		        </div>
        	</div> --}}
        	<div class="col-md-4">
		        <label for="images" class="control-label">Foto*</label>

		        <div class="field_wrapper">
			        <div class="form-group">
				        <input type="file" name="images[]" style="display: inline;" accept="image/x-png, image/jpeg">
		        		<a href="javascript:void(0);" class="add_button btn btn-xs btn-success pull-right" title="Add Field"><i class="fa fa-plus"></i></a>
			        </div>
		        </div>
		        @if($errors->has('images'))
                    <span class="invalid-feedback" role="alert">
                        {{ $errors->first('images') }}
                    </span>
                @endif
        	</div>
        </div>

        <hr>
        <h4>Owner</h4>
        <div class="row">
        	<div class="col-md-4">
                <div class="form-group">
                    <label for="owner_name" class="control-label">Nama Lengkap*</label>
                    {!! Form::text('owner_name', null, ['class'=>'form-control', 'id'=>'owner_name']) !!}

                    @if($errors->has('owner_name'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('owner_name') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
                <div class="form-group">
                    <label for="owner_ktp_number" class="control-label">Nomor KTP*</label>
                    {!! Form::text('owner_ktp_number', null, ['class'=>'form-control', 'id'=>'owner_ktp_number']) !!}

                    @if($errors->has('owner_ktp_number'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('owner_ktp_number') }}
                        </span>
                    @endif
                </div>
        	</div>
        	<div class="col-md-4">
        		<div class="form-group">
                    <label for="owner_kk_number" class="control-label">Nomor KK*</label>
                    {!! Form::text('owner_kk_number', null, ['class'=>'form-control', 'id'=>'owner_kk_number']) !!}

                    @if($errors->has('owner_kk_number'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('owner_kk_number') }}
                        </span>
                    @endif
                </div>
        	</div>
        </div>
        <div class="row">
        	<div class="col-md-4">
                <div class="form-group">
                    <label for="active" class="control-label">Active</label>
                    <div>
                        {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
                    </div>

                    @if($errors->has('active'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('active') }}
                        </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        {!! Form::submit('Create', ['class'=>'btn btn-primary pull-right']) !!}
    </div>
    {!! Form::close() !!}
</div>
@endsection

@push('scripts')
<script>
	var maxField = 10,
		addButton = $('.add_button'),
		wrapper = $('.field_wrapper'),
		fieldHtml = '<div class="form-group"><input type="file" name="images[]" style="display: inline;" accept="image/x-png, image/jpeg"><a href="javascript:void(0);" class="remove_button btn btn-xs btn-danger pull-right" title="Remove"><i class="fa fa-close"></i></a></div>',
		x = 1;

	$(addButton).click(function(){
		if(x < maxField){
			x++;
			$(wrapper).append(fieldHtml);
		}
	});

	$(wrapper).on('click', '.remove_button', function(e){
        e.preventDefault();
        $(this).parent('div').remove(); //Remove field html
        // document.getElementsByClassName("form-group").remove();
        x--; //Decrement field counter
    });

</script>
@endpush

resources/views/master/asset/index.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Asset @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('asset.create') }}" class="btn btn-success" title="Create Asset">
                <i class="fa fa-plus"></i> Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <button class="btn btn-sm btn-danger btn-mass-delete"><i class="fa fa-trash"></i></button>
        </div>
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        {{-- <th></th> --}}
                        <th>No</th>
                        <th>Asset name</th>
                        <th>Category</th>
                        <th>Owner Name</th>
                        <th>Created By</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.asset') }}",
            columns: [
                // {data : 'checkbox', name : 'checkbox'},
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'asset_name', name : 'asset_name'},
                {data : 'category', name : 'category'},
                {data : 'owner_name', name : 'owner_name'},
                {data : 'created_by', name : 'created_by'},
                {data : 'created_at', name : 'created_at'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush