routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        // Member Type
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        // Class
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
		// Bank
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');
        // Asset Category
        Route::resource('asset-category', 'PdtCategoryAssetController');
        Route::get('table/asset-category', 'PdtCategoryAssetController@dataTable')->name('table.asset-category');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        // Employee
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        // Banner
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        // Asset
        Route::resource('asset', 'PdtAssetController');
        Route::get('table/asset', 'PdtAssetController@dataTable')->name('table.asset');
    });
    // Setting
    Route::group(['prefix'=>'setting'], function(){
       // Module
        Route::resource('menu', 'SecModuleController');
        Route::get('table/menu', 'SecModuleController@dataTable')->name('table.menu'); 
    });
		
	Route::get('/master/class_price','ClassPriceController@index');
	Route::get('/master/class_price/create','ClassPriceController@create');
	Route::get('/master/class_price/delete/{id}','ClassPriceController@destroy');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::post('/master/class_price/post_price/','ClassPriceController@store');
	Route::post('/master/class_price/edit_price/{id}','ClassPriceController@update');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::get('/master/class_price/show/{id}','ClassPriceController@show');
	
	Route::get('/master/country','CountryController@index');
	Route::get('/master/country/create','CountryController@create');
	Route::post('/master/country/post_country','CountryController@store');
	Route::get('/master/country/edit/{id}','CountryController@edit');
	Route::post('/master/country/edit_country/{id}','CountryController@update');
	Route::get('/master/country/import','CountryController@import');
	Route::post('/master/country/proses_import','CountryController@proses_import');

	Route::get('/master/province','ProvinceController@index');
	Route::get('/master/province/create','ProvinceController@create');
	Route::post('/master/province/post_province','ProvinceController@store');
	Route::post('/master/province/edit_province/{id}','ProvinceController@update');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/edit/{id}','ProvinceController@edit');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/import','ProvinceController@import');
	Route::post('/master/province/import_province','ProvinceController@import_province');
	
	Route::get('/master/regency','RegencyController@index');
	Route::get('/master/regency/create','RegencyController@create');
	Route::post('/master/regency/post_regency','RegencyController@store');
	Route::get('/master/regency/edit_regency/{id}','RegencyController@edit');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/delete_regency/{id}','RegencyController@destroy');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/import','RegencyController@import');
	Route::post('/master/regency/import_post_regency','RegencyController@import_regency');
	
	Route::get('/master/district','DistrictController@index');
	Route::get('/master/district/create','DistrictController@create');
	Route::post('/master/district/post_district','DistrictController@store');
	Route::get('master/district/edit/{id}','DistrictController@edit');
	Route::post('/master/district/edit_district/{id}','DistrictController@update');
	Route::get('/master/district/delete_district/{id}','DistrictController@destroy');
	Route::get('/master/district/import','DistrictController@import');
	Route::post('/master/district/import_district','DistrictController@import_district');
	
	Route::get('/master/village','VillageController@index');
	Route::get('/master/village/create','VillageController@create');
	Route::post('/master/village/post_village','VillageController@store');
	Route::get('master/village/edit_village/{id}','VillageController@edit');
	Route::post('/master/village/edit_village_post/{id}','VillageController@update');
	Route::get('/master/village/delete_village/{id}','VillageController@destroy');
	Route::get('/master/village/import','VillageController@import');
	Route::post('/master/village/import_village','VillageController@import_village');
	
	
	Route::get('/master/data_address','MstAddressController@index');
	Route::get('/master/address/create','MstAddressController@create');
	Route::get('/master/address/province/{id}','MstAddressController@province');
	Route::get('/master/address/regency/{id}','MstAddressController@regency');
	Route::get('/master/address/district/{id}','MstAddressController@district');
	Route::get('/master/address/village/{id}','MstAddressController@village');
	Route::post('/master/address/post_address','MstAddressController@store');
});





// Route::get('/home', 'HomeController@index')->name('home');

resources/views/master/banner/action-position.blade.php
<a href="{{ $url_destroy }}" class="btn-delete3 btn btn-xs btn-danger" title="Delete"><i class="fa fa-trash"></i></a>

resources/views/master/banner/action.blade.php
<a href="{{ $url_show }}" class="btn btn-xs btn-primary" title="Detail {{ $model->title }}"><i class="fa fa-search"></i></a>
<a href="{{ $url_setposition }}" class="btn btn-xs btn-primary" title="Set Position {{ $model->title }}"><i class="fa fa-map-marker"></i></a>
<a href="{{ $url_edit }}" class="btn btn-xs btn-primary" title="Edit {{ $model->title }}"><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete {{ $model->title }}"><i class="fa fa-trash"></i></a>

resources/views/master/banner/create.blade.php
@extends('base.main')
@section('title') Banner @endsection
@section('page_icon') <i class="fa fa-image"></i> @endsection
@section('page_title') Create Banner @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('banner.index') }}" class="btn btn-success" title="Manage">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
	{!! Form::model($model, [
	    'route' => 'banner.store',
	    'method'=> 'post',
	    'enctype'	=> 'multipart/form-data'
	]) !!}
	<div class="box-body">
		@if(count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
					<li>{{  $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
		<div class="form-group">
		    <label for="title" class="control-label">Title*</label>
		    {!! Form::text('title', null, ['class'=>'form-control', 'id'=>'title']) !!}

		    @if($errors->has('title'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('title') }}
		    	</span>
		    @endif
		</div>
		<div class="form-group">
		    <label for="subtitle" class="control-label">Subtitle*</label>
		    {!! Form::text('subtitle', null, ['class'=>'form-control', 'id'=>'subtitle']) !!}

		    @if($errors->has('subtitle'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('subtitle') }}
		    	</span>
		    @endif
		</div>
		<div class="form-group">
            <label for="desc" class="control-label">Description*</label>
            {!! Form::textarea('desc', null, ['class'=>'textarea form-control', 'id'=>'desc', 'rows'=>6]) !!}

            @if($errors->has('desc'))
                <span class="invalid-feedback" role="alert">
                    {{ $errors->first('desc') }}
                </span>
            @endif
        </div>
        <div class="row">
        	<div class="col-md-6">
        		<div class="form-group">
				    <label for="image" class="control-label">Image</label>
				    {!! Form::file('image', ['accept'=>'image/x-png, image/jpeg']) !!}

				    @if($errors->has('image'))
				    	<span class="invalid-feedback" role="alert">
				    		{{ $errors->first('image') }}
				    	</span>
				    @endif
				</div>
        	</div>
        	<div class="col-md-6">
        		<div class="form-group">
				    <label for="video" class="control-label">Video</label>
				    {!! Form::file('video', ['accept'=>'video/*']) !!}

				    @if($errors->has('video'))
				    	<span class="invalid-feedback" role="alert">
				    		{{ $errors->first('video') }}
				    	</span>
				    @endif
				</div>
        	</div>
        </div>
        <div class="form-group">
			<label for="iframe" class="control-label">iFrame</label>
            {!! Form::textarea('iframe', null, ['class'=>'form-control', 'id'=>'iframe', 'rows'=>3]) !!}

            @if($errors->has('iframe'))
                <span class="invalid-feedback" role="alert">
                    {{ $errors->first('iframe') }}
                </span>
            @endif
        </div>
        <div class="form-group">
		    <label for="active" class="control-label">Active</label>
		    <div>
		        {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
		    </div>
		    @if($errors->has('active'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('active') }}
		    	</span>
		    @endif
		</div>
	</div>
	<div class="box-footer">
		{!! Form::submit('Create', ['class'=>'btn btn-primary pull-right']) !!}
	</div>
	{!! Form::close() !!}
</div>
@endsection

resources/views/master/banner/detail.blade.php
@extends('base.main')
@section('title') Banner @endsection
@section('page_icon') <i class="fa fa-image"></i> @endsection
@section('page_title') Banner Detail @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
        	<a href="{{ route('banner.setposition', $model->id) }}" class="btn btn-success" title="Set Position Banner">
                <i class="fa fa-map-marker"></i> Set Position
            </a>
            <a href="{{ route('banner.edit', $model->id) }}" class="btn btn-success" title="Edit Banner">
                <i class="fa fa-edit"></i> Update
            </a>
            <a href="{{ route('banner.delete', $model->id) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
        	<a href="{{ route('banner.create') }}" class="btn btn-success" title="Create Banner">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('banner.index') }}" class="btn btn-success" title="Manage">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
	<div class="box-body">
		<h4>Detail</h4>
		<div class="row">
			<div class="col-md-6">
				<table class="table table-condensed table-striped">
					<tbody>
						<tr>
							<th>Title</th>
							<td>{!! $model->title !!}</td>
						</tr>
						<tr>
							<th>Subtitle</th>
							<td>{!! $model->subtitle !!}</td>
						</tr>
						<tr>
							<th>Description</th>
							<td>{!! html_entity_decode($model->desc) !!}</td>
						</tr>
						<tr>
							<th>Active</th>
							<td>{{ $model->active == 1 ? 'Ya' : 'Tidak' }}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="col-md-6">
				<table class="table table-condensed table-striped">
					<tbody>
						<tr>
							<th>Created By</th>
							<td>{{ $uti->getUser($model->created_by) }}</td>
						</tr>
						<tr>
							<th>Created Date</th>
							<td>{{ date('d-m-Y H:i:s', strtotime($model->created_at)) }}</td>
						</tr>
						<tr>
							<th>Updated By</th>
							<td>{{ $uti->getUser($model->updated_by) }}</td>
						</tr>
						<tr>
							<th>Updated Date</th>
							<td>{{ date('d-m-Y H:i:s', strtotime($model->updated_at)) }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-7">
				<h4>Attachment</h4>
				<table class="table table-condensed table-striped">
					<tbody>
						<tr><th>Image</th></tr>
						<tr><td>
							@if($model->image == null)
								<img src="{{ asset('images/no-img.png') }}" class="img-responsive img-thumbnail">
							@else
								<img src="{{ asset('images/banner/'.$model->image) }}" class="img-responsive">
							@endif
						</td></tr>
						<tr><th>Video</th></tr>
						<tr><td>
							@if($model->video == null)
								<img src="{{ asset('images/no-img.png') }}" class="img-responsive img-thumbnail">
							@else
								<video width="440" height="300" controls>
									<source src="{{ asset('video/banner/'.$model->video) }}" type="video/mp4">
									<source src="{{ asset('video/banner/'.$model->video) }}" type="video/ogg">
									Your browser does not support the video
								</video>
							@endif
						</td></tr>
						<tr><th>iFrame</th></tr>
						<tr><td>{!! html_entity_decode($model->iframe) !!}</td></tr>
					</tbody>
				</table>
			</div>
			<div class="col-md-5">
				<h4>Position</h4>
				<table class="table table-striped table-condensed">
					<thead>
						<tr>
							<th>Page</th>
							<th>Position</th>
							<th>Order</th>
						</tr>
					</thead>
					<tbody>
						@foreach($detail as $row)
							<tr>
								<td>{{ $row->page }}</td>
								<td>{{ $row->position }}</td>
								<td>{{ $row->order }}</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/master/banner/index.blade.php
@extends('base.main')
@section('title') Banner @endsection
@section('page_icon') <i class="fa fa-image"></i> @endsection
@section('page_title') Banner @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('banner.create') }}" class="btn btn-success" title="Create Banner">
                <i class="fa fa-plus"></i> Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <button class="btn btn-sm btn-danger btn-mass-delete"><i class="fa fa-trash"></i></button>
        </div>
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        {{-- <th></th> --}}
                        <th>No</th>
                        <th>Title</th>
                        <th>Created By</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.banner') }}",
            columns: [
                // {data : 'checkbox', name : 'checkbox'},
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'title', name : 'title'},
                {data : 'created_by', name : 'created_by'},
                {data : 'created_at', name : 'created_at'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush

resources/views/master/banner/setposition.blade.php
@extends('base.main')
@section('title') Banner @endsection
@section('page_icon') <i class="fa fa-image"></i> @endsection
@section('page_title') Set Banner Position @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('banner.show', $model->id) }}" class="btn btn-success" title="Detail">
                <i class="fa fa-search"></i> Detail
            </a>
            <a href="{{ route('banner.edit', $model->id) }}" class="btn btn-success" title="Edit Banner">
                <i class="fa fa-edit"></i> Update
            </a>
            <a href="{{ route('banner.delete', $model->id) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
            <a href="{{ route('banner.create') }}" class="btn btn-success" title="Create Banner">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('banner.index') }}" class="btn btn-success" title="Manage">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
	<div class="box-body">
		{!! Form::open(['method'=> 'post', 'route'=>'banner.set', 'id'=>'setposition-form']) !!}
			{!! Form::hidden('banner',$model->id,['id'=>'banner']) !!}
		<div class="row">
			<div class="col-md-3">
				<div class="form-group">
					<label for="page" class="control-label">Page*</label>
					{!! Form::select('page', [''=>'- Select -']+$page, null, ['class'=>'form-control dynamic', 'id'=>'page']) !!}

					@if($errors->has('page'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('page') }}
                        </span>
                    @endif
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<label for="position" class="control-label">Position*</label>
					<select name="position" id="position" class="form-control">
                        <option value="">- Select -</option>
                    </select>

                    @if($errors->has('position'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('position') }}
                        </span>
                    @endif
				</div>
			</div>
			<div class="col-md-3">
				<div class="form-group">
					<label for="order" class="control-label">Order</label>
					{!! Form::text('order', null, ['class'=>'form-control', 'id'=>'order']) !!}

					@if($errors->has('order'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('order') }}
                        </span>
                    @endif
				</div>
			</div>
			<div class="col-md-3">
				{!! Form::submit('Add', ['class'=>'btn btn-primary btn-add','style'=>'margin-top:25px;']) !!}
			</div>
		</div>
		{!! Form::close() !!}
	</div>
	<div class="box-footer">
		<table id="datatable" class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Page</th>
                    <th>Position</th>
                    <th>Order</th>
                    <th>Action</th>
                </tr>
            </thead>
        </table>
	</div>
	<div class="box-footer">
		<a href="{{ route('banner.show', $model->id) }}" class="btn btn-success pull-right"><i class="fa fa-check"></i> Finish</a>
	</div>
</div>
@endsection

@push('scripts')
<script>

    $('.dynamic').change(function(){
        if($(this).val() != ''){
            var value = $(this).val(),
                token = $('input[name="_token"]').val();

            $.ajax({
                url : "{{ route('banner.fetch') }}",
                method : 'post',
                data : {
                    value : value,
                    _token : token
                },
                success : function(result){
                    $('#position').html(result);
                }
            });
        }
    });

    $('.btn-add').click(function(e){
    	e.preventDefault();

    	var url = $('#setposition-form').attr('action');

    	$.ajax({
    		url : url,
    		method : 'post',
    		data : $('#setposition-form').serialize(),
    		success : function(response){
    			$('#setposition-form').trigger('reset');
    			$('#datatable').DataTable().ajax.reload();

	            swal({
	                type : 'success',
	                title : 'Success',
	                text : 'Berhasil'
	            });
    		},
    		error : function(e){
	            var response = e.responseJSON;
	            if($.isEmptyObject(response) == false)
	            {
	                $.each(response.errors, function(key, value) {
	                    $('#' + key)
	                        .closest('.form-group')
	                        .addClass('has-error')
	                        .append('<span class="help-block">'+ value +'</span>')
	                });

	                swal({
		                type : 'error',
		                title : 'Failed',
		                text : response.errors
		            });
	            }
	        }
    	});
    });

    $('#datatable').DataTable({
        responsive : true,
        processing : true,
        serverSide : true,
        ajax: "{{ route('table.banner.position', $model->id) }}",
        columns: [
            {data : 'DT_Row_Index', name : 'position_id'},
            {data : 'page', name : 'page'},
            {data : 'position', name : 'position'},
            {data : 'order', name : 'order'},
            {data : 'action', name : 'action'}
        ]
    });
</script>
@endpush

resources/views/master/banner/update.blade.php
@extends('base.main')
@section('title') Banner @endsection
@section('page_icon') <i class="fa fa-image"></i> @endsection
@section('page_title') Edit Banner @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('banner.show', $model->id) }}" class="btn btn-success" title="Detail">
                <i class="fa fa-search"></i> Detail
            </a>
            <a href="{{ route('banner.setposition', $model->id) }}" class="btn btn-success" title="Set Position Banner">
                <i class="fa fa-map-marker"></i> Set Position
            </a>
            <a href="{{ route('banner.delete', $model->id) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
            <a href="{{ route('banner.create') }}" class="btn btn-success" title="Create Banner">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('banner.index') }}" class="btn btn-success" title="Manage">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
	{!! Form::model($model, [
	    'route' => ['banner.update', $model->id],
	    'method'=> 'put',
	    'enctype'	=> 'multipart/form-data'
	]) !!}
	<div class="box-body">
		@if(count($errors) > 0)
			<div class="alert alert-danger">
				<ul>
					@foreach($errors->all() as $error)
					<li>{{  $error }}</li>
					@endforeach
				</ul>
			</div>
		@endif
		<div class="form-group">
		    <label for="title" class="control-label">Title*</label>
		    {!! Form::text('title', null, ['class'=>'form-control', 'id'=>'title']) !!}

		    @if($errors->has('title'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('title') }}
		    	</span>
		    @endif
		</div>
		<div class="form-group">
		    <label for="subtitle" class="control-label">Subtitle*</label>
		    {!! Form::text('subtitle', null, ['class'=>'form-control', 'id'=>'subtitle']) !!}

		    @if($errors->has('subtitle'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('subtitle') }}
		    	</span>
		    @endif
		</div>
		<div class="form-group">
            <label for="desc" class="control-label">Description*</label>
            {!! Form::textarea('desc', null, ['class'=>'textarea form-control', 'id'=>'desc', 'rows'=>6]) !!}

            @if($errors->has('desc'))
                <span class="invalid-feedback" role="alert">
                    {{ $errors->first('desc') }}
                </span>
            @endif
        </div>
        <div class="row">
        	<div class="col-md-6">
        		<div class="form-group">
        			@if($model->image == null)
						<img src="{{ asset('images/no-img.png') }}" class="img-responsive img-thumbnail">
					@else
						<img src="{{ asset('images/banner/'.$model->image) }}" class="img-responsive">
					@endif
        		</div>
        		<div class="form-group">
				    <label for="image" class="control-label">Image</label>
				    {!! Form::file('image', ['accept'=>'image/x-png, image/jpeg']) !!}

				    @if($errors->has('image'))
				    	<span class="invalid-feedback" role="alert">
				    		{{ $errors->first('image') }}
				    	</span>
				    @endif
				</div>
        	</div>
        	<div class="col-md-6">
        		<div class="form-group">
        			@if($model->video == null)
						<img src="{{ asset('images/no-img.png') }}" class="img-responsive img-thumbnail">
					@else
						<video width="320" height="240" controls>
							<source src="{{ asset('video/banner/'.$model->video) }}" type="video/mp4">
							<source src="{{ asset('video/banner/'.$model->video) }}" type="video/ogg">
							Your browser does not support the video
						</video>
					@endif
        		</div>
        		<div class="form-group">
				    <label for="video" class="control-label">Video</label>
				    {!! Form::file('video', ['accept'=>'video/*']) !!}

				    @if($errors->has('video'))
				    	<span class="invalid-feedback" role="alert">
				    		{{ $errors->first('video') }}
				    	</span>
				    @endif
				</div>
        	</div>
        </div>
        <div class="form-group">
			<label for="iframe" class="control-label">iFrame</label>
            {!! Form::textarea('iframe', null, ['class'=>'form-control', 'id'=>'iframe', 'rows'=>3]) !!}

            @if($errors->has('iframe'))
                <span class="invalid-feedback" role="alert">
                    {{ $errors->first('iframe') }}
                </span>
            @endif
        </div>
        <div class="form-group">
		    <label for="active" class="control-label">Active</label>
		    <div>
		        {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
		    </div>
		    @if($errors->has('active'))
		    	<span class="invalid-feedback" role="alert">
		    		{{ $errors->first('active') }}
		    	</span>
		    @endif
		</div>
	</div>
	<div class="box-footer">
		{!! Form::submit('Save', ['class'=>'btn btn-primary pull-right']) !!}
	</div>
	{!! Form::close() !!}
</div>
@endsection