routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        // Member Type
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        // Class
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
		// Bank
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');
        // Asset Category
        Route::resource('asset-category', 'PdtCategoryAssetController');
        Route::get('table/asset-category', 'PdtCategoryAssetController@dataTable')->name('table.asset-category');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        // Employee
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        // Banner
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        // Asset
        Route::resource('asset', 'PdtAssetController');
        Route::get('table/asset', 'PdtAssetController@dataTable')->name('table.asset');
    });
    // Setting
    Route::group(['prefix'=>'setting'], function(){
       // Module
        Route::resource('menu', 'SecModuleController');
        Route::get('table/menu', 'SecModuleController@dataTable')->name('table.menu'); 
    });
		
	Route::get('/master/class_price','ClassPriceController@index');
	Route::get('/master/class_price/create','ClassPriceController@create');
	Route::get('/master/class_price/delete/{id}','ClassPriceController@destroy');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::post('/master/class_price/post_price/','ClassPriceController@store');
	Route::post('/master/class_price/edit_price/{id}','ClassPriceController@update');
	Route::get('/master/class_price/edit/{id}','ClassPriceController@edit');
	Route::get('/master/class_price/show/{id}','ClassPriceController@show');
	
	Route::get('/master/country','CountryController@index');
	Route::get('/master/country/create','CountryController@create');
	Route::post('/master/country/post_country','CountryController@store');
	Route::get('/master/country/edit/{id}','CountryController@edit');
	Route::post('/master/country/edit_country/{id}','CountryController@update');
	Route::get('/master/country/import','CountryController@import');
	Route::post('/master/country/proses_import','CountryController@proses_import');

	Route::get('/master/province','ProvinceController@index');
	Route::get('/master/province/create','ProvinceController@create');
	Route::post('/master/province/post_province','ProvinceController@store');
	Route::post('/master/province/edit_province/{id}','ProvinceController@update');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/edit/{id}','ProvinceController@edit');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/import','ProvinceController@import');
	Route::post('/master/province/import_province','ProvinceController@import_province');
	
	Route::get('/master/regency','RegencyController@index');
	Route::get('/master/regency/create','RegencyController@create');
	Route::post('/master/regency/post_regency','RegencyController@store');
	Route::get('/master/regency/edit_regency/{id}','RegencyController@edit');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/delete_regency/{id}','RegencyController@destroy');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/import','RegencyController@import');
	Route::post('/master/regency/import_post_regency','RegencyController@import_regency');
	
	Route::get('/master/district','DistrictController@index');
	Route::get('/master/district/create','DistrictController@create');
	Route::post('/master/district/post_district','DistrictController@store');
	Route::get('master/district/edit/{id}','DistrictController@edit');
	Route::post('/master/district/edit_district/{id}','DistrictController@update');
	Route::get('/master/district/delete_district/{id}','DistrictController@destroy');
	Route::get('/master/district/import','DistrictController@import');
	Route::post('/master/district/import_district','DistrictController@import_district');
	
	Route::get('/master/village','VillageController@index');
	Route::get('/master/village/create','VillageController@create');
	Route::post('/master/village/post_village','VillageController@store');
	Route::get('master/village/edit_village/{id}','VillageController@edit');
	Route::post('/master/village/edit_village_post/{id}','VillageController@update');
	Route::get('/master/village/delete_village/{id}','VillageController@destroy');
	Route::get('/master/village/import','VillageController@import');
	Route::post('/master/village/import_village','VillageController@import_village');
	
	
	Route::get('/master/data_address','MstAddressController@index');
	Route::get('/master/address/create','MstAddressController@create');
	Route::get('/master/address/province/{id}','MstAddressController@province');
	Route::get('/master/address/regency/{id}','MstAddressController@regency');
	Route::get('/master/address/district/{id}','MstAddressController@district');
	Route::get('/master/address/village/{id}','MstAddressController@village');
	Route::post('/master/address/post_address','MstAddressController@store');
});





// Route::get('/home', 'HomeController@index')->name('home');

resources/views/master/member/action.blade.php
<a href="{{ $url_show }}" class="btn-show btn btn-xs btn-primary" title="Detail {{ $model->member }}"><i class="fa fa-search"></i></a>
<a href="{{ $url_edit }}" class="modal-show btn btn-xs btn-primary edit" title="Edit {{ $model->member }}"><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete {{ $model->member }}"><i class="fa fa-trash"></i></a>

resources/views/master/member/create.blade.php
@extends('base.main')
@section('title') Role @endsection
@section('page_icon') <i class="fa fa-book"></i> @endsection
@section('page_title') Role @endsection
@section('page_subtitle') create @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('role.index') }}" class="btn btn-default"><i class="fa fa-list"></i> Manage</a>
        </div>
    </div>
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="box box-solid">
        <form action="{{ route('role.store') }}" method="post" >
            @csrf
            <div class="box-body">
                <div class="form-group">
                    <label for="nama">Nama<span class="required">*</span></label>
                    <input type="text" name="nama" id="nama" class="form-control">
                </div>

                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="active" id="active" value="0" > Active
                    </label>
                </div>

                <div class="form-group">
                    <label for="created_by">Created by<span class="required">*</span></label>
                    <input type="text" name="created_by" id="created_by" class="form-control">
                </div>
                <div class="form-group">
                    <label for="created_by">Updated by<span class="required">*</span></label>
                    <input type="text" name="updated_by" id="updated_by" class="form-control">
                </div>
            </div>
            <div class="box-footer" style="text-align:right;">
                <input type="submit" value="Save" class="btn btn-primary">
            </div>
        </form>
    </div>
@endsection

resources/views/master/member/detail.blade.php
<table class="table table-striped table-condensed">
	<tr>
		<th>Nama Member</th>
		<td>{{ $model->member }}</td>
	</tr>
	<tr>
		<th>Active</th>
		<td>{{ $model->active == 1 ? 'Ya' : 'Tidak' }}</td>
	</tr>
	<tr>
		<th>Created By</th>
		<td>{{ $uti->getUser($model->created_by) }}</td>
	</tr>
	<tr>
		<th>Created Date</th>
		<td>{{ date('d-m-Y H:i:s', strtotime($model->created_at)) }}</td>
	</tr>
	<tr>
		<th>Updated By</th>
		<td>{{ $uti->getUser($model->updated_by) }}</td>
	</tr>
	<tr>
		<th>Updated Date</th>
		<td>{{ date('d-m-Y H:i:s', strtotime($model->updated_at)) }}</td>
	</tr>
</table>

resources/views/master/member/edit.blade.php
@extends('base.main')
@section('title') Role @endsection
@section('page_icon') <i class="fa fa-book"></i> @endsection
@section('page_title') Role @endsection
@section('page_subtitle') create @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('role.index') }}" class="btn btn-default"><i class="fa fa-list"></i> Manage</a>
        </div>
    </div>
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="box box-solid">


        @foreach($data as $datas)
            <form action="{{ route('role.update', $datas->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="box-body">
                    <div class="form-group">
                        <label for="nama">Nama<span class="required">*</span></label>
                        <input type="text" name="nama" id="nama" class="form-control" value="{{ $datas->nama }}">
                    </div>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="active" id="active" value="{{ $datas->active }}"> Active
                        </label>
                    </div>

                    <div class="form-group">
                        {{--<label for="created_by">Created by<span class="required">*</span></label>--}}
                        <input type="hidden" name="created_by" id="created_by" class="form-control"
                               value="{{ $datas->created_by }}" >
                    </div>
                    <div class="form-group">
                        {{--    <label for="created_by">Updated by<span class="required">*</span></label>--}}
                        <input type="hidden" name="updated_by" id="updated_by" class="form-control"
                               value="{{ $datas->updated_by }}">
                    </div>
                </div>
                <div class="box-footer" style="text-align:right;">
                    <input type="submit" value="Save" class="btn btn-danger">
                </div>
            </form>
        @endforeach
    </div>
@endsection

resources/views/master/member/form.blade.php
@php
    $method = $model->exists ? 'PUT' : 'POST';
@endphp
{!! Form::model($model, [
    'route' => $model->exists ? ['member.update', $model->id] : 'member.store',
    'method'=> $method,
]) !!}

    <div class="form-group">
        <label for="member" class="control-label">Nama Member</label>
        {!! Form::text('member', null, ['class'=>'form-control', 'id'=>'member']) !!}
    </div>

    <div class="form-group">
        <label for="active" class="control-label">Active</label>
        <div>
            {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
        </div>
    </div>

{!! Form::close() !!}

resources/views/master/member/index.blade.php
@extends('base.main')
@section('title') Member @endsection
@section('page_icon') <i class="fa fa-user"></i> @endsection
@section('page_title') Member @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('member.create') }}" class="btn btn-success modal-show" title="Create Member">
                <i class="fa fa-plus"></i> Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="box box-solid">
        <div class="box-header">
            <button class="btn btn-sm btn-danger btn-mass-delete"><i class="fa fa-trash"></i></button>
        </div>
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        {{-- <th></th> --}}
                        <th>No</th>
                        <th>Nama Member</th>
                        <th>Created By</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.member') }}",
            columns: [
                // {data : 'checkbox', name : 'checkbox'},
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'member', name : 'member'},
                {data : 'created_by', name : 'created_by'},
                {data : 'created_at', name : 'created_at'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush